# Generated by Django 6.0.2 on 2026-03-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
