# Generated by Django 6.0.2 on 2026-03-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiapp', '0002_studentprofile_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='target_company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='target_role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
