# Generated by Django 5.2 on 2026-04-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiapp', '0003_studentprofile_target_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
